import React, { useEffect, useState } from "react";
import { View, StyleSheet, Dimensions } from "react-native";
import Carousel from "react-native-snap-carousel";
import { ActivityIndicator, Card, Text } from "react-native-paper";
import {
  getAutogeneratedPlaylist,
  getFavorites,
} from "@/components/api/request";
import { backgroundImage } from "@/constants/Styles";
import { Image } from "react-native-elements";

const favorites = [
  {
    id: 1,
    name: "Favorite 1",
    description: "Description for favorite 1",
    poster: "https://via.placeholder.com/100",
  },
  {
    id: 2,
    name: "Favorite 2",
    description: "Description for favorite 2",
    poster: "https://via.placeholder.com/100",
  },
  // Add more favorites as needed
];

const { width } = Dimensions.get("window");

const Favorites = () => {
  const [error, setError] = useState<string | null>(null);
  const [favorites, setFavorites] = useState([]); // Replace with actual data
  const [loading, setLoading] = useState<boolean>(false);
  const [autogeneratedPlaylist, setAutogeneratedPlaylist] = useState([]);
  const renderItem = ({
    item,
  }: {
    item: { id: number; title: string; description: string; poster: string };
  }) => (
    <Card style={styles.item}>
      <View style={{ flex: 1, width: 500, height: 240 }}>
        <Image
          PlaceholderContent={<ActivityIndicator />}
          source={{ uri: backgroundImage }}
          style={styles.poster}
        />
      </View>
      <Card.Content style={styles.details}>
        <Text style={styles.title}>{item.title}</Text>
        <Text style={styles.description}>{item.description}</Text>
      </Card.Content>
    </Card>
  );

  useEffect(() => {
    getFavorites({ setFavorites, setError, setLoading });
    getAutogeneratedPlaylist({
      setAutogeneratedPlaylist,
      setError,
      setLoading,
    });
    // console.log(favorites, autogeneratedPlaylist[0]);
  }, []);

  return (
    <View style={styles.container}>
      <View style={styles.textContainer}>
        <Text style={styles.titleText}>
          {favorites.length > 0 ? "Favorites" : "Autogenerated Playlist"}
        </Text>
      </View>
      <Carousel
        data={favorites.length > 0 ? favorites : autogeneratedPlaylist}
        renderItem={renderItem}
        sliderWidth={width}
        itemWidth={width * 0.6}
        inactiveSlideScale={0.85}
        inactiveSlideOpacity={0.7}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  textContainer: {
    width: "100%",
    padding: 16,
  },
  titleText: {
    fontSize: 20,
    fontWeight: "bold",
  },
  item: {
    flexDirection: "row",
    alignItems: "center",

    marginVertical: 8,
    borderRadius: 8,
    height: 200,
    position: "relative",
  },
  poster: {
    width: "100%",
    height: "100%",
  },
  details: {
    flex: 1,
    marginLeft: 10,
    top: 150,
    justifyContent: "center",
    position: "absolute",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFF",
  },
  description: {
    fontSize: 14,
    color: "#666",
  },
});

export default Favorites;
